;!knitout-2
;;Machine: SWG091N2
;;Gauge: 15
;;Position: Right
;;Carriers: 1 2 3 4 5 6 7 8 9 10
inhook 1; from line 5 of Right swatch
tuck - b7 1;Right Shifted for Merge from line 6 of Right swatch
tuck - f6 1;Right Shifted for Merge from line 7 of Right swatch
tuck - b5 1;Right Shifted for Merge from line 8 of Right swatch
tuck - f4 1;Right Shifted for Merge from line 9 of Right swatch
tuck - b3 1; from line 6 of Left swatch
tuck - f2 1; from line 7 of Left swatch
tuck - b1 1; from line 8 of Left swatch
tuck - f0 1; from line 9 of Left swatch
tuck + b0 1; from line 10 of Left swatch
tuck + f1 1; from line 11 of Left swatch
tuck + b2 1; from line 12 of Left swatch
tuck + f3 1; from line 13 of Left swatch
tuck + b4 1;Right Shifted for Merge from line 10 of Right swatch
tuck + f5 1;Right Shifted for Merge from line 11 of Right swatch
tuck + b6 1;Right Shifted for Merge from line 12 of Right swatch
tuck + f7 1;Right Shifted for Merge from line 13 of Right swatch
releasehook 1; from line 14 of Right swatch
inhook 2; from line 15 of Right swatch
knit - b7 2;Right Shifted for Merge from line 16 of Right swatch
knit - f6 2;Right Shifted for Merge from line 17 of Right swatch
knit - b5 2;Right Shifted for Merge from line 18 of Right swatch
knit - f4 2;Right Shifted for Merge from line 19 of Right swatch
knit - b3 2; from line 16 of Left swatch
knit - f2 2; from line 17 of Left swatch
knit - b1 2; from line 18 of Left swatch
knit - f0 2; from line 19 of Left swatch
knit + b0 2; from line 20 of Left swatch
knit + f1 2; from line 21 of Left swatch
knit + b2 2; from line 22 of Left swatch
knit + f3 2; from line 23 of Left swatch
knit + b4 2;Right Shifted for Merge from line 20 of Right swatch
knit + f5 2;Right Shifted for Merge from line 21 of Right swatch
knit + b6 2;Right Shifted for Merge from line 22 of Right swatch
knit + f7 2;Right Shifted for Merge from line 23 of Right swatch
releasehook 2; from line 24 of Right swatch
knit - b7 1;Right Shifted for Merge from line 25 of Right swatch
knit - b6 1;Right Shifted for Merge from line 26 of Right swatch
knit - f5 1;Right Shifted for Merge from line 27 of Right swatch
knit - f4 1;Right Shifted for Merge from line 28 of Right swatch
knit - b3 1; from line 25 of Left swatch
knit - b2 1; from line 26 of Left swatch
knit - f1 1; from line 27 of Left swatch
knit - f0 1; from line 28 of Left swatch
knit - f7 2;Right Shifted for Merge from line 29 of Right swatch
knit - f6 2;Right Shifted for Merge from line 30 of Right swatch
knit - b5 2;Right Shifted for Merge from line 31 of Right swatch
knit - b4 2;Right Shifted for Merge from line 32 of Right swatch
knit - f3 2; from line 29 of Left swatch
knit - f2 2; from line 30 of Left swatch
knit - b1 2; from line 31 of Left swatch
knit - b0 2; from line 32 of Left swatch
outhook 1;Outhook remaining active carriers
outhook 2;Outhook remaining active carriers
